const locators = require('../fixtures/locators.json')
const faker = require('faker')
describe ('registration' , ()=> {
    beforeEach(() => {
        cy.visit("https://gallery-app.vivifyideas.com/")
        cy.get(locators.register.navgationRegister).click()
    })

    it.only('required first-name input field', ()=> {
        cy.get(locators.register.lastName).clear().type(faker.name.lastName())
        cy.get(locators.register.email).clear().type(faker.internet.email())
        cy.get(locators.register.password).clear().type(faker.internet.password())
        cy.get(locators.register.passwordConfirmation).clear().type(faker.internet.password())
        cy.get(locators.register.checkbox).check()
        cy.get(locators.register.submit).click()
    })
    it('required last-name input field',()=> {
        cy.get(locators.register.firstName).clear().type(faker.internet.firstName)
        cy.get(locators.register.email).clear().type('branatest.test.com')
        cy.get(locators.register.password).clear().type('12345678')
        cy.get(locators.register.passwordConfirmation).clear().type('12345678')
        cy.get(locators.register.checkbox).check()
        cy.get(locators.register.submit).click()
    })
    it('registration without "@" character', ()=> {
        cy.get(locators.register.firstName).clear().type('Brana')
        cy.get(locators.register.lastName).clear().type('Mila')
        cy.get(locators.register.email).clear().type('branatest.test.com')
        cy.get(locators.register.password).clear().type('12345678')
        cy.get(locators.register.passwordConfirmation).clear().type('12345678')
        cy.get(locators.register.checkbox).check()
        cy.get(locators.register.submit).click()
    })
    it('registration without email address', ()=> {
        cy.get(locators.register.firstName).clear().type('Brana')
        cy.get(locators.register.lastName).clear().type('Mila')
        cy.get(locators.register.password).clear().type('12345678')
        cy.get(locators.register.passwordConfirmation).clear().type('12345678')
        cy.get(locators.register.checkbox).check()
        cy.get(locators.register.submit).click()
    })
    it('registraton without password', ()=> {
        cy.get(locators.register.firstName).clear().type('Brana')
        cy.get(locators.register.lastName).clear().type('Mila')
        cy.get(locators.register.email).clear().type('branatest@test.com')
        cy.get(locators.register.passwordConfirmation).clear().type('12345678')
        cy.get(locators.register.checkbox).check()
        cy.get(locators.register.submit).click()
    })
    it('Password and confirm password must be the same', ()=> {
        cy.get(locators.register.firstName).type('Brana')
        cy.get(locators.register.lastName).type('Mila')
        cy.get(locators.register.email).type('branatest@test.com')
        cy.get(locators.register.password).type('123456789')
        cy.get(locators.register.passwordConfirmation).type('12345678')
        cy.get(locators.register.checkbox).check()
        cy.get(locators.register.submit).click()
    })
    it('Password length must have minimum 8 characters', ()=> {
        cy.get(locators.register.firstName).type('Brana')
        cy.get(locators.register.lastName).type('Mila')
        cy.get(locators.register.email).type('branatest@test.com')
        cy.get(locators.register.password).type('1234')
        cy.get(locators.register.passwordConfirmation).type('1234')
        cy.get(locators.register.checkbox).check()
        cy.get(locators.register.submit).click()
    })
    it('Password format is invalid', ()=> {
        cy.get(locators.register.firstName).type('Brana')
        cy.get(locators.register.lastName).type('Mila')
        cy.get(locators.register.email).type('branatest@test.com')
        cy.get(locators.register.password).type('branislava')
        cy.get(locators.register.passwordConfirmation).type('branislava')
        cy.get(locators.register.checkbox).check()
        cy.get(locators.register.submit).click()
    })
    it('Password format is invalid', ()=> {
        cy.get(locators.register.firstName).type('Brana')
        cy.get(locators.register.lastName).type('Mila')
        cy.get(locators.register.email).type('branatest@test.com')
        cy.get(locators.register.password).type('12345678')
        cy.get(locators.register.passwordConfirmation).type('12345678')
        cy.get(locators.register.checkbox).check()
        cy.get(locators.register.submit).click()
    })
    it('dot is used in wrong position', ()=> {
        cy.get(locators.register.firstName).type('Brana')
        cy.get(locators.register.lastName).type('Mila')
        cy.get(locators.register.email).type('branatest@test.')
        cy.get(locators.register.password).type('12345678')
        cy.get(locators.register.passwordConfirmation).type('12345678')
        cy.get(locators.register.checkbox).check()
        cy.get(locators.register.submit).click()
    })
})