describe ('registration' , ()=> {
    it( 'visit gallery page' , () => {
        cy.visit("/")
    })
    it('registrationPage', ()=> {
        cy.get('li:nth-of-type(2) > .nav-buttons.nav-link').click()
    })
    it('required first-name input field', ()=> {
        cy.get('#first-name').type('').clear()
        cy.get('#last-name').type('Mila').clear()
        cy.get('#email').type('branatest@test.com').clear()
        cy.get('#password').type('12345678').clear()
        cy.get('#password-confirmation').type('12345678').clear()
        cy.get('input[type=checkbox]').check().uncheck()
        cy.get('button[type=submit]').click()
    })
    it('required last-name input field',()=> {
        cy.get('#first-name').type('Brana').clear()
        cy.get('#last-name').type().clear()
        cy.get('#email').type('branatest.test.com').clear()
        cy.get('#password').type('12345678').clear()
        cy.get('#password-confirmation').type('12345678').clear()
        cy.get('input[type=checkbox]').check().uncheck()
        cy.get('button[type=submit]').click()
    })
    it('registration without "@" character', ()=> {
        cy.get('#first-name').type('Brana').clear()
        cy.get('#last-name').type('Mila').clear()
        cy.get('#email').type('branatest.test.com').clear()
        cy.get('#password').type('12345678').clear()
        cy.get('#password-confirmation').type('12345678').clear()
        cy.get('input[type=checkbox]').check().uncheck()
        cy.get('button[type=submit]').click()
    })
    it('registration without email address', ()=> {
        cy.get('#first-name').type('Brana').clear()
        cy.get('#last-name').type('Mila').clear()
        cy.get('#email').type().clear()
        cy.get('#password').type('12345678').clear()
        cy.get('#password-confirmation').type('12345678').clear()
        cy.get('input[type=checkbox]').check().uncheck()
        cy.get('button[type=submit]').click()
    })
    it('registraton without password', ()=> {
        cy.get('#first-name').type('Brana').clear()
        cy.get('#last-name').type('Mila').clear()
        cy.get('#email').type('branatest@test.com').clear()
        cy.get('#password').type().clear()
        cy.get('#password-confirmation').type('12345678').clear()
        cy.get('input[type=checkbox]').check().uncheck()
        cy.get('button[type=submit]').click()
    })
    it('Password and confirm password must be the same', ()=> {
        cy.get('#first-name').type('Brana').clear()
        cy.get('#last-name').type('Mila').clear()
        cy.get('#email').type('branatest@test.com').clear()
        cy.get('#password').type('123456789').clear()
        cy.get('#password-confirmation').type('12345678').clear()
        cy.get('input[type=checkbox]').check().uncheck()
        cy.get('button[type=submit]').click()
    })
    it('Password length must have minimum 8 characters', ()=> {
        cy.get('#first-name').type('Brana').clear()
        cy.get('#last-name').type('Mila').clear()
        cy.get('#email').type('branatest@test.com').clear()
        cy.get('#password').type('1234').clear()
        cy.get('#password-confirmation').type('1234').clear()
        cy.get('input[type=checkbox]').check().uncheck()
        cy.get('button[type=submit]').click()
    })
    it('Password format is invalid', ()=> {
        cy.get('#first-name').type('Brana').clear()
        cy.get('#last-name').type('Mila').clear()
        cy.get('#email').type('branatest@test.com').clear()
        cy.get('#password').type('branislava').clear()
        cy.get('#password-confirmation').type('branislava').clear()
        cy.get('input[type=checkbox]').check().uncheck()
        cy.get('button[type=submit]').click()
    })
    it('Password format is invalid', ()=> {
        cy.get('#first-name').type('Brana').clear()
        cy.get('#last-name').type('Mila').clear()
        cy.get('#email').type('branatest@test.com').clear()
        cy.get('#password').type('12345678').clear()
        cy.get('#password-confirmation').type('12345678').clear()
        cy.get('input[type=checkbox]').uncheck()
        cy.get('button[type=submit]').click()
    })
    it('dot is used in wrong position', ()=> {
        cy.get('#first-name').type('Brana').clear()
        cy.get('#last-name').type('Mila').clear()
        cy.get('#email').type('branatest@test.').clear()
        cy.get('#password').type('12345678').clear()
        cy.get('#password-confirmation').type('12345678').clear()
        cy.get('input[type=checkbox]').check().uncheck()
        cy.get('button[type=submit]').click()
    })
})